More logging, limit to one change per config call, and fixed date parsing on removal.
morphy2k/k8s-mongo-sidecar pull request #75
Opened 2020-08-28 06:15 UTC by jhughes2112

Mongo 4.4.0 is stricter about only allowing one add or remove at a time, and no changes while an add or remove is taking place.  That means we can't add or remove multiple pods at once.  So I added a limit for that, except in the case where we are forcing.

There was a parsing error (at least for me) that left my removal broken.  The date was parsed as NaN somehow.  Switched to Date.parse and it got sorted out.  Now when I scale down, pods are really removed from the ReplicaSet, when they weren't before.

Since I'm not a JS programmer, I had to add a decent amount of logging to figure things out.  I left them in, but commented out the noisy ones so they won't waste log space, in case someone wants to work on this further, it's easier to get started.

Testing:  Scaling the statefulset from 2 -> 5 worked fine, deleting the primary worked fine, and scaling from 5 -> 1 worked fine.

2020-08-29 10:43 UTC, morphy2k commented
Thank you for the PR!
Could you please run `npm run lint` or use the ESLint extension for your editor and fix the linting errors?

2020-10-28 22:12 UTC, terrpan commented
Any chance of getting this merged?

2020-10-28 22:46 UTC, jhughes2112 commented
If you want to give my changes a run through their paces, I have an image at this commit on Docker Hub at https://hub.docker.com/r/jhughes2112/k8s-mongo-sidecar

2020-10-29 00:42 UTC, morphy2k requested changes
Sorry for the delay, has unfortunately gone under.

2020-10-29 00:42 UTC, morphy2k commented on package.json
> +    "eslint": "^7.7.0",
Please keep the old dependency version.

2020-10-29 00:42 UTC, morphy2k commented on package.json
> +    "eslint-config-strongloop": "^2.1.0"
Why? Please don't add or change any ESLint rules

2020-10-29 00:42 UTC, morphy2k commented on src/lib/worker.js
> +    console.info('Running on host '+hostIpAndPort+' hostname '+hostName);
Could you insert spaces here?
```suggestion
    console.info('Running on host ' + hostIpAndPort + ' hostname ' + hostName);
```

There are a few more lines

2020-10-29 00:42 UTC, morphy2k commented on src/lib/worker.js
> +  }
```suggestion
  if (!member.health) {
    const lastHeartbeatTick = Date.parse(member.lastHeartbeatRecv);
    const nowTick = DateTime.utc();
    console.info('Member: ' + member.name + ' Last Heartbeat: ' + lastHeartbeatTick + '  Now: ' + nowTick);
    if (nowTick - lastHeartbeatTick > unhealthySeconds*1000) return true;
  }
```

2020-10-29 01:36 UTC, jhughes2112 commented
Thanks for the code review.  Unfortunately, I've already put more time into this project than I had allocated.  I don't use Mongo anymore, so I have no way to test the changes, and as I mentioned above, I don't write JS code for a living.  Feel free to make whatever changes you like, take them, leave them, it's up to you.

2020-10-29 01:36 UTC, closed without merging